### ISSUE TITLE
Echo2 gebruikt commons-fileupload:1.4

### ISSUE THREAD

**Issue by nielsm5** [wearefrank/ladybug#198]
Of we moeten dit patchen in echo2, of in de ibis-ladybug.pom.

**Comment by jacodg** [comment]
https://github.com/wearefrank/ladybug-echo2/commit/b6fb5d89e7c8163665cdd792419a0f21f8aef9b2
https://github.com/wearefrank/ladybug-echo2/commit/9fd9bb3eff4a13b95c11505166c34a028ed624fc
