### ISSUE TITLE
Skipped pipes show as if they were executed anyways

### ISSUE THREAD

**Issue by MLenterman** [wearefrank/ladybug#212]
If a pipe is skipped because of an IfParam or IfSessionKey condition, it still shows as if it was executed anyways. The output of the pipe and the storeResultInSessionKey sessionkey are both showing the input of the pipe. The only indication that a pipe was skipped is that the output and storeResultInSessionKey sessionkey look off.

Greying out skipped pipes or any other indication that a pipe was skipped would be very handy.

**Comment by jacodg** [comment]
Can you create an issue at the F!F project? Ladybug doesn't know about pipes, it has generic methods to create reports with checkpoint that can have any name or content. F!F creates checkpoints with names like Pipeline and Pipe

**Comment by MLenterman** [comment]
https://github.com/frankframework/frankframework/issues/6654
