### ISSUE TITLE
Ladybug doesn't wait for database connection

### ISSUE THREAD

**Issue by philipsens** [wearefrank/ladybug#223]
When starting both a database management system and Frank! at the same time, the Ladybug will try to connect to the starting database, which isn't possible. This crashes the Frank!.

In Docker or in a testing environment, it is very common to start all programs at once. 

The Frank!Framework had the same issue. Although it already did some waiting while the database was starting, we were also having some troubles with a couple of databases, like DB2. I made an issue for this: https://github.com/frankframework/frankframework/issues/5046
This might not be a complete solution for the problem with the ladybug, but I think it'll still be useful.

The Frank!Framework has some failed tests in the CI/CD. The logs can be found here:
* https://jenkins.frankframework.org/job/ff-ci/job/larva/28833/
* https://jenkins.frankframework.org/job/ff-ci/job/larva/28832/
* https://jenkins.frankframework.org/job/ff-ci/job/larva/28775/
* https://jenkins.frankframework.org/job/ff-ci/job/larva/28774/
* https://jenkins.frankframework.org/job/ff-ci/job/larva/28778/

**Comment by jacodg** [comment]
See https://github.com/frankframework/frankframework/pull/6474
