### ISSUE TITLE
The exit state of a pipeline is shown with a right arrow, I would expect a left arrow

### ISSUE THREAD

**Issue by mhdirkse** [wearefrank/ladybug#275]
In ladybug I have the following report in the debug tree:

![image](https://github.com/user-attachments/assets/c186d136-e270-4c89-a9fb-2ec8b8f07ca9)

The exit states of the nested pipelines are shown with a right arrow. I would expect that a right arrow stands for "input", because start checkpoints and incoming session keys have a right arrow. End checkpoints are shown with a left arrow, output. Exit states are also outputs and hence I would expect a left arrow.

**Comment by MarkvdVorst** [comment]
What is the checkpoint type shown in the metadata? Because as shown in a couple arrows bellow, output points do aim to the left and input point aim to the right.

**Comment by mhdirkse** [comment]
Should be an FF! issue, see https://github.com/frankframework/frankframework/issues/7260.
