### ISSUE TITLE
Rerunning a report succeeds while an output message is different

### ISSUE THREAD

**Issue by mhdirkse** [wearefrank/ladybug#277]
I copied a report to the test tab and then I edited it. I wanted to see that rerunning a report can fail. Instead, the report succeeded. When I clicked compare I could see the difference I expected from my edit:

![image](https://github.com/user-attachments/assets/3ec8d91a-04d8-415b-9edc-36cf9aa28f4b)

I would expect that rerunning this report would fail.

**Comment by jacodg** [comment]
The default xslt will only get the first and last message of the report which are then compared to determine success or not. You can change the xslt or make the person name end up in the last checkpoint

**Comment by mhdirkse** [comment]
@jacodg and @MatthijsSmets, does this mean we can close this issue?
