### ISSUE TITLE
Rerunning a ladybug report succeeds unexpectedly

### ISSUE THREAD

**Issue by mhdirkse** [wearefrank/ladybug#284]
I had a report in the test tab that I wanted to rerun. I edited it with the intention to let it fail. Rerunning succeeded however.

I clicked Compare to see whether my edit had taken effect. It had according to the following screenshot:

![image](https://github.com/user-attachments/assets/4c3cd21c-5dc3-4278-83b3-a7227ac07c1a)

**Comment by MatthijsSmets** [comment]
I have transferred this to the backend repository as this is not a frontend problem.

**Comment by mhdirkse** [comment]
Het resultaat is met de nieuwste code van ladybug, ladybug-frontend en frankframework iets anders:

![Image](https://github.com/user-attachments/assets/d80edd9a-1725-4d8c-ae02-cc5ae7ccca4f)

Als ik naar de root node ga dan zie ik dit:

![Image](https://github.com/user-attachments/assets/3b2974d5-19c2-45c1-a8df-bcbdbe2dffe7)

Dit is lang niet alle XML die ik had verwacht; heeft er misschien mee te maken dat de black box view geselecteerd is. Maar als ik de white box view selecteer dan zie ik nog steeds maar twee checkpoints.

**Comment by mhdirkse** [comment]
Lijkt op https://github.com/wearefrank/ladybug-frontend/issues/664

**Comment by mhdirkse** [comment]
Ik heb een meeting ingeschoten met @MatthijsSmets en @jacodg om samen naar het gedrag van de compare tab te kijken.

**Comment by mhdirkse** [comment]
Je ziet in het screenshot dat je aan dezelfde kant meerdere nodes tegelijk kan selecteren. Daar is issue https://github.com/wearefrank/ladybug-frontend/issues/682 voor.

**Comment by mhdirkse** [comment]
Dit issue kan denk ik gesloten worden. De XML die je ziet is de XML die je verkrijgt na het toepassen van de XSLT transformatie (de transformatie opgeslagen bij het rapport of de default als die ontbreekt). De default XSLT transformatie bewaart alleen het eerste en het laatste checkpoint. Een test faalt als de XML documenten na toepassen van de XSLT verschillen.

Ik heb in deze test een tussengelegen checkpoint ge-edit. Dat was niet de goede manier om het te testen.
